DEV_CONTAINER = {
    "Ubuntu Base": "ubuntu",
    "Alpine Linux": "alpine",
    "Debian Base": "debian",
    "Arch Linux": "archlinux",
    "Python": "python",
    "Node.js": "node",
    "Golang": "golang",
    "Rust": "rust",
    "Java": "openjdk",
    "C/C++": "gcc",
    "Swift": "swift",
    "Ruby": "ruby",
    "PHP": "php",
    "Kotlin": "openjdk",
    "Django": "django",
    "Flask": "python",
    "Express.js": "node",
    "Laravel": "bitnami/laravel",
    "Spring Boot": "openjdk",
    "NestJS": "node",
    "PostgreSQL": "postgres",
    "MySQL": "mysql",
    "MariaDB": "mariadb",
    "Redis": "redis",
    "MongoDB": "mongo",
    "Neo4j": "neo4j",
    "Elasticsearch": "elasticsearch",
    "Jupyter Notebook": "jupyter/base-notebook",
    "TensorFlow": "tensorflow/tensorflow",
    "PyTorch": "pytorch/pytorch",
    "NVIDIA CUDA": "nvidia/cuda",
    "Docker-in-Docker": "docker",
    "Kubernetes": "rancher/k3s",
    "Terraform": "hashicorp/terraform",
    "Ansible": "willhallonline/ansible",
    "Metasploit": "metasploitframework/metasploit-framework",
    "OWASP ZAP": "owasp/zap2docker-stable",
    "Kali Linux": "kalilinux/kali-rolling",
    "Unity": "game-ci/unity3d",
    "Godot": "barichello/godot",
}
docker_file = {
    "Alpine Linux": "Alpine.flowburst",
    "Django": "Django.flowburst",
    "Godot": "Godot.flowburst",
    "Kotlin": "Kotlin.flowburst",
    "MongoDB": "MongoDB.flowburst",
    "PHP": "PHP.flowburst",
    "Ruby": "Ruby.flowburst",
    "Terraform": "Terraform.flowburst",
    "Ansible": "Ansible.flowburst",
    "Docker-in-Docker": "Docker-in-Docker.flowburst",
    "Golang": "Golang.flowburst",
    "Kubernetes": "Kubernetes.flowburst",
    "MySQL": "MySQL.flowburst",
    "PostgreSQL": "PostgreSQL.flowburst",
    "Rust": "Rust.flowburst",
    "Ubuntu Base": "Ubuntu.flowburst",
    "Arch Linux": "Arch.flowburst",
    "Elasticsearch": "Elasticsearch.flowburst",
    "Java": "Java.flowburst",
    "Laravel": "Laravel.flowburst",
    "Neo4j": "Neo4j.flowburst",
    "Python": "Python.flowburst",
    "Node.js": "Node.flowburst",
    "Spring Boot": "Spring.flowburst",
    "Unity": "Unity.flowburst",
    "C/C++": "C-cpp.flowburst",
    "Express.js": "Express.flowburst",
    "Jupyter Notebook": "Jupyter.flowburst",
    "MariaDB": "MariaDB.flowburst",
    "NestJS": "NestJS.flowburst",
    "PyTorch": "PyTorch.flowburst",
    "Swift": "Swift.flowburst",
    "OWASP ZAP": "ZAP.flowburst",
    "Debian Base": "Debian.flowburst",
    "Flask": "Flask.flowburst",
    "Kali Linux": "Kali.flowburst",
    "Metasploit": "Metasploit.flowburst",
    "NVIDIA CUDA": "NVIDIA.flowburst",
    "Redis": "Redis.flowburst",
    "TensorFlow": "TensorFlow.flowburst",
}
